### ISSUE TITLE
vagrant - oc1 cinder failure seen

### ISSUE THREAD

**Issue by saneax** [JioCloud/puppet-rjil#322]
Notice: /Stage[main]/Rjil::Cinder::Backup/Ceph::Auth[cinder-backup]/Exec[exec_add_ceph_auth_cinder-backup]/returns: no monitors specified to connect to.
Notice: /Stage[main]/Rjil::Cinder::Backup/Ceph::Auth[cinder-backup]/Exec[exec_add_ceph_auth_cinder-backup]/returns: Error connecting to cluster: ObjectNotFound
Notice: /Stage[main]/Rjil::Cinder::Backup/Ceph::Auth[cinder-backup]/Exec[exec_add_ceph_auth_cinder-backup]/returns: Option --add-key requires an argument.
Error: ceph-authtool /etc/ceph/keyring.ceph.client.cinder_backup                   --name=client.cinder-backup --add-key                   $(ceph --name mon. --key 'AQBRSfNSQNCMAxAA/wSNgHmHwzjnl2Rk22P4jA=='                   auth get-or-create-key client.cinder-backup  mon "allow r" osd "allow class-read object_prefix rbd_children, allow rwx pool=backups")
                 returned 1 instead of one of [0]
Error: /Stage[main]/Rjil::Cinder::Backup/Ceph::Auth[cinder-backup]/Exec[exec_add_ceph_auth_cinder-backup]/returns: change from notrun to 0 failed: ceph-authtool /etc/ceph/keyring.ceph.client.cinder_backup                   --name=client.cinder-backup --add-key                   $(ceph --name mon. --key 'AQBRSfNSQNCMAxAA/wSNgHmHwzjnl2Rk22P4jA=='                   auth get-or-create-key client.cinder-backup  mon "allow r" osd "allow class-read object_prefix rbd_children, allow rwx pool=backups")
                 returned 1 instead of one of [0]

**Comment by saneax** [comment]
ok this is because ceph did not get configured properly. rerun of provisioning solved this.

**Comment by bodepd** [comment]
in general, you probably should have done a little more diagnostics before submitted an issue here. Things to generally try:

- does it fail everytime puppet ran? puppet runs continuously b/c things just fail sometimes, we generally like to be aware of, but aren't concerned by failures that are recoverable
- what happens when you run the command directly from the command line?
- is it possible that the failure really occurred somewhere else and cascaded here?
