### ISSUE TITLE
Duplicate statement in build_scripts/deploy.sh

### ISSUE THREAD

**Issue by sajuptpm** [JioCloud/puppet-rjil#352]
Following statement duplicated in build_scripts/deploy.sh

$(python -m jiocloud.utils get_ip_of_node ${consul_bootstrap_node:-etcd1}_${project_tag})

**Comment by bodepd** [comment]
I don't know, it's probably better in this case to submit a patch. It's probably a bug, that line should be moved up.

**Comment by sorenh** [comment]
I'm pretty sure that's intentional. The first instance of this is repeated over and over in a loop in a subshell (running under timeout) to handle the case where the floating ip takes a while to appear.

Once that loop is terminated succesfully, we look up the ip once again to make it available to the remainder of the script.

@bodepd  , you wrote this code, didn't you? :)

**Comment by bodepd** [comment]
@sorenh you are correct. It is a scoping issue caused by the fact that timeout is using a subshell. I didn't think hard enough...

**Comment by bodepd** [comment]
specifically, it can't be moved before, b/c we need to be robust enough to handle the case where no ip gets returned from that statement (ie: it needs to retry until an ip is ready, but that ip can't be reused b/c it is in the scope of the subshell)
